spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration/dev
    baseline-on-migrate: true
    validate-on-migrate: true

    # En el application-dev.yml de Orders
    user:
      service:
        url: ${USER_SERVICE_URL}
    product:
      service:
        url: ${PRODUCT_SERVICE_URL}

